package entities;
// Generated Nov 7, 2018 3:46:26 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name="images"
    ,catalog="thuenha24h"
)
public class Images  implements java.io.Serializable {


     private int id;
     private Poster poster;
     private String name;

    public Images() {
    }

    public Images(int id, Poster poster, String name) {
       this.id = id;
       this.poster = poster;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_poster", nullable=false)
    public Poster getPoster() {
        return this.poster;
    }
    
    public void setPoster(Poster poster) {
        this.poster = poster;
    }

    
    @Column(name="name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


