package entities;
// Generated Nov 7, 2018 3:46:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poster generated by hbm2java
 */
@Entity
@Table(name="poster"
    ,catalog="thuenha24h"
)
public class Poster  implements java.io.Serializable {


     private int id;
     private Category category;
     private String name;
     private String email;
     private String title;
     private String info;
     private String address;
     private Set<Images> imageses = new HashSet<Images>(0);
     private Set<Comments> commentses = new HashSet<Comments>(0);

    public Poster() {
    }

	
    public Poster(int id, Category category, String name, String email, String title, String info, String address) {
        this.id = id;
        this.category = category;
        this.name = name;
        this.email = email;
        this.title = title;
        this.info = info;
        this.address = address;
    }
    public Poster(int id, Category category, String name, String email, String title, String info, String address, Set<Images> imageses, Set<Comments> commentses) {
       this.id = id;
       this.category = category;
       this.name = name;
       this.email = email;
       this.title = title;
       this.info = info;
       this.address = address;
       this.imageses = imageses;
       this.commentses = commentses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_category", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="title", nullable=false, length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="info", nullable=false, length=999)
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }

    
    @Column(name="address", nullable=false, length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poster")
    public Set<Images> getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set<Images> imageses) {
        this.imageses = imageses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poster")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }




}


